# Generated by Django 3.1.3 on 2020-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Номер телефона')),
                ('name', models.CharField(max_length=512, verbose_name='ФИО')),
                ('total_bonus', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общий бонус')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Номер карты')),
            ],
        ),
    ]
