# Generated by Django 3.1.3 on 2020-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_number',
            field=models.CharField(max_length=16, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_bonus',
            field=models.IntegerField(default=0, null=True, verbose_name='Общий бонус'),
        ),
    ]
